name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore NetBridge.sln

      - run: dotnet build NetBridge.sln --configuration Release --no-restore

      - name: Pack NuGet packages
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          VERSION=${VERSION#v}
          dotnet pack src/NetBridge.Abstractions/NetBridge.Abstractions.csproj --configuration Release -p:PackageVersion=$VERSION -o ./nupkg
          dotnet pack src/NetBridge.Dispatching/NetBridge.Dispatching.csproj --configuration Release -p:PackageVersion=$VERSION -o ./nupkg
          dotnet pack src/NetBridge.Messaging/NetBridge.Messaging.csproj --configuration Release -p:PackageVersion=$VERSION -o ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate